on: push
name: build and test app
jobs:
  build:
    name: install dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: install dependencies
        uses: steebchen/flutter@v2.2.3
        with:
          args: pub get

      - name: build apk
        uses: steebchen/flutter@v2.2.3
        with:
          args: build apk --release
